//! Checks the Rust core against vectors recorded from the frozen prototype.
//!
//! Regenerate with `node tools/extract-golden/extract.js`.

use swept_core::geometry::{Obb, Point, PointDistance};
use swept_core::kinematics::Pose;
use swept_core::units::Radians;

/// Largest acceptable difference from the prototype, in metres or radians.
const TOLERANCE: f64 = 1e-9;

/// Pulls every `"name": value` pair out of a flat JSON fixture, in order.
///
/// The fixtures are generated by our own tool and have a known, flat shape, so
/// a full JSON parser would be a dependency this crate deliberately refuses.
fn scalars(json: &str, name: &str) -> Vec<f64> {
    let needle = format!("\"{name}\":");
    json.match_indices(&needle)
        .map(|(at, _)| {
            let rest = &json[at + needle.len()..];
            let end = rest.find([',', '}', ']', '\n']).unwrap_or(rest.len());
            rest[..end]
                .trim()
                .parse::<f64>()
                .unwrap_or_else(|_| panic!("field {name} is not a number: {}", &rest[..end]))
        })
        .collect()
}

/// Same, for boolean fields.
fn flags(json: &str, name: &str) -> Vec<bool> {
    let needle = format!("\"{name}\":");
    json.match_indices(&needle)
        .map(|(at, _)| json[at + needle.len()..].trim_start().starts_with("true"))
        .collect()
}

#[test]
fn matches_the_prototype_on_point_to_rectangle_distance() {
    let json = include_str!("fixtures/geometry.json");
    let cx = scalars(json, "cx");
    let cy = scalars(json, "cy");
    let ang = scalars(json, "ang");
    let hw = scalars(json, "hw");
    let hh = scalars(json, "hh");
    let px = scalars(json, "x");
    let py = scalars(json, "y");
    let expected = scalars(json, "distance_to_a");

    assert!(
        !expected.is_empty(),
        "fixtures are missing; run the extractor"
    );

    for (case, want) in expected.iter().enumerate() {
        // Each case records rectangle a then rectangle b, so a is at index 2i.
        let i = case * 2;
        let obb = Obb::new(Point::new(cx[i], cy[i]), Radians::new(ang[i]), hw[i], hh[i]);
        let got = match obb.distance_to(Point::new(px[case], py[case])) {
            PointDistance::Inside => -1.0,
            PointDistance::Outside(d) => d,
        };
        assert!(
            (got - want).abs() < TOLERANCE,
            "case {case}: prototype says {want}, core says {got}"
        );
    }
}

#[test]
fn matches_the_prototype_on_rectangle_overlap() {
    let json = include_str!("fixtures/geometry.json");
    let cx = scalars(json, "cx");
    let cy = scalars(json, "cy");
    let ang = scalars(json, "ang");
    let hw = scalars(json, "hw");
    let hh = scalars(json, "hh");
    let expected = flags(json, "overlaps");

    assert!(
        !expected.is_empty(),
        "fixtures are missing; run the extractor"
    );

    for (case, want) in expected.iter().enumerate() {
        let (i, j) = (case * 2, case * 2 + 1);
        let a = Obb::new(Point::new(cx[i], cy[i]), Radians::new(ang[i]), hw[i], hh[i]);
        let b = Obb::new(Point::new(cx[j], cy[j]), Radians::new(ang[j]), hw[j], hh[j]);
        assert_eq!(a.overlaps(&b), *want, "case {case}");
    }
}

#[test]
fn matches_the_prototype_on_constant_curvature_integration() {
    let json = include_str!("fixtures/kinematics.json");
    let xs = scalars(json, "x");
    let ys = scalars(json, "y");
    let ths = scalars(json, "th");
    let curvature = scalars(json, "curvature");
    let distance = scalars(json, "distance");

    assert!(
        !curvature.is_empty(),
        "fixtures are missing; run the extractor"
    );

    for case in 0..curvature.len() {
        // Each case records start then end, so start is at index 2i.
        let (s, e) = (case * 2, case * 2 + 1);
        let start = Pose::new(xs[s], ys[s], Radians::new(ths[s]));
        let got = start.advance(curvature[case], distance[case]);

        assert!((got.x - xs[e]).abs() < TOLERANCE, "case {case}: x");
        assert!((got.y - ys[e]).abs() < TOLERANCE, "case {case}: y");
        assert!(
            (got.heading.get() - ths[e]).abs() < TOLERANCE,
            "case {case}: heading"
        );
    }
}
